services:
  serverstatus:
    build:
      context: ..
      dockerfile: Dockerfile
    image: looprt/serverstatus_server
    container_name: serverstatus
    restart: unless-stopped
    networks:
      serverstatus-network:
        ipv4_address: 172.23.0.2
    volumes:
      - ../server/config.json:/ServerStatus/server/config.json
      - ../web/json:/usr/share/nginx/html/json
    ports:
      - 35601:35601
      - 8080:80
  bot:
    build:
      context: .
      dockerfile: Dockerfile-pushplus
    image: looprt/serverstatus_bot:pushplus
    container_name: bot4sss
    restart: unless-stopped
    networks:
      serverstatus-network:
        ipv4_address: 172.23.0.3
    environment:
      - PP_BOT_TOKEN=${PP_BOT_TOKEN}
      - SERVER_DOMAIN=${SERVER_DOMAIN}

networks:
  serverstatus-network:
    name: serverstatus-network
    ipam:
      config:
        - subnet: 172.23.0.0/24
