FROM python:alpine

LABEL maintainer="jumploop"
LABEL version="0.0.1"
LABEL description="ServerChan Bot for ServerStatus"

WORKDIR /app
RUN pip install requests  \
    && apk --no-cache add -U curl \
    && curl -1sLf "https://raw.githubusercontent.com/jumploop/ServerStatus/master/plugin/bot-serverchan.py" | tee bot-serverchan.py \
    && apk del curl

CMD [ "python", "./bot-serverchan.py" ]
